# Generated by Django 4.0.6 on 2022-08-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('clave', models.CharField(blank=True, max_length=4, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('customer_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.TextField()),
                ('customer_surname', models.TextField()),
                ('customer_dni', models.TextField(db_column='customer_DNI')),
                ('dob', models.TextField(blank=True, null=True)),
                ('customer_address_id', models.IntegerField(blank=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField()),
                ('iban', models.TextField()),
                ('account_type', models.TextField(blank=True, null=True)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.TextField()),
                ('number', models.IntegerField()),
                ('city', models.TextField()),
                ('province', models.TextField()),
                ('country', models.TextField()),
            ],
            options={
                'db_table': 'direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.TextField()),
                ('employee_surname', models.TextField()),
                ('employee_hire_date', models.TextField()),
                ('employee_dni', models.TextField(db_column='employee_DNI')),
                ('branch_id', models.IntegerField()),
                ('employee_address_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarcaTarjeta',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.TextField()),
            ],
            options={
                'db_table': 'marca_tarjeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_type', models.TextField()),
                ('loan_date', models.TextField()),
                ('loan_total', models.IntegerField()),
                ('customer_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prestamo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_number', models.BinaryField()),
                ('branch_name', models.TextField()),
                ('branch_address_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sucursal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_card', models.CharField(max_length=200, unique=True)),
                ('cvv', models.IntegerField()),
                ('issue_date', models.TextField()),
                ('exp_date', models.TextField()),
                ('type_card', models.TextField()),
                ('customer_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tarjeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('customer_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.TextField(unique=True)),
                ('debit_card', models.TextField()),
                ('credit_card', models.TextField()),
                ('current_account', models.TextField()),
                ('checkbook_amount', models.IntegerField()),
                ('box_dollar', models.TextField(blank=True, null=True)),
                ('box_peso', models.TextField(blank=True, null=True)),
                ('withdraw_daily_max', models.IntegerField(blank=True, null=True)),
                ('transfer_comission', models.IntegerField(blank=True, null=True)),
                ('max_travel_reception', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_cliente',
                'managed': False,
            },
        ),
    ]
