# Generated by Django 4.0.6 on 2022-09-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.TextField()),
                ('customer_surname', models.TextField()),
                ('customer_dni', models.TextField(db_column='customer_DNI')),
                ('dob', models.TextField(blank=True, null=True)),
                ('customer_address_id', models.IntegerField(blank=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, db_column='User_id', max_length=254, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.TextField()),
                ('number', models.IntegerField()),
                ('city', models.TextField()),
                ('province', models.TextField()),
                ('country', models.TextField()),
            ],
            options={
                'db_table': 'direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('customer_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.TextField(unique=True)),
                ('debit_card', models.TextField()),
                ('credit_card', models.TextField()),
                ('current_account', models.TextField()),
                ('checkbook_amount', models.IntegerField()),
                ('box_dollar', models.TextField(blank=True, null=True)),
                ('box_peso', models.TextField(blank=True, null=True)),
                ('withdraw_daily_max', models.IntegerField(blank=True, null=True)),
                ('transfer_comission', models.IntegerField(blank=True, null=True)),
                ('max_travel_reception', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_cliente',
                'managed': False,
            },
        ),
    ]
